- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - box
  - bagel
  - cog
  - core
  - corvax_astra
  - corvax_avrite
  - corvax_delta
  - corvax_frame
  - corvax_ishimura
  - corvax_maus
  - corvax_paper
  - fland
  - marathon
  - meta
