# Юридический отдел
- type: job
  id: Justice
  name: судья
  description: Организуйте судебные процессы, нотариально заверяйте документы, рассматривайте обвинения и при необходимости выступайте в качестве судьи.
  playTimeTracker: JobJustice
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobLawyerr
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobProsecutor
      time: 36000 # 10 hours
    - !type:AgeRequirement
      requiredAge: 21
  startingGear: HoPGear
  icon: "JobIconJustice"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Security

#- type: startingGear
#  id: JusticeGear
#  equipment:
#    jumpsuit:
#    back:
#    shoes:
#    id:
#    ears:
#  innerClothingSkirt:
#  satchel:
#  duffelbag:
