# Юридический отдел
- type: job
  id: Justice
  name: job-name-justice
  description: job-description-justice
  playTimeTracker: JobJustice
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobLawyer
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobProsecutor
      time: 36000 # 10 hours
    - !type:AgeRequirement
      requiredAge: 21
  startingGear: HoPGear
  icon: "JobIconJustice"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Security
  - Lawyer
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

#- type: startingGear
#  id: JusticeGear
#  equipment:
#    jumpsuit:
#    back:
#    shoes:
#    id:
#    ears:
#  innerClothingSkirt:
#  satchel:
#  duffelbag:
