# Юридический отдел
- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 hours
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
    - !type:AgeRequirement
      requiredAge: 21
  startingGear: HoPGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj
  access:
  - Security
  - Brig
  - Lawyer
  - Service
  - External
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlue
    back: ClothingBackpack
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetJustice
  inhand:
  - BriefcaseLawyer
