# Юридический отдел
- type: job
  id: Prosecutor
  name: job-name-prosecutor
  description: job-description-prosecutor
  playTimeTracker: JobProsecutor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
    - !type:AgeRequirement
      requiredAge: 21
  startingGear: HoPGear
  icon: "JobIconProsecutor"
  supervisors: job-supervisors-cj
  access:
  - Security
  - Brig
  - Lawyer
  - Service
  - External
  - Maintenance

- type: startingGear
  id: ProsecutorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerRed
    back: ClothingBackpack
    shoes: ClothingShoesBootsLaceup
    id: ProsecutorPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetJustice
  inhand:
  - BriefcaseProsecutor
